version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t sean-test .
      - docker tag sean-test:latest 194783185645.dkr.ecr.ap-southeast-2.amazonaws.com/sean-test:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 194783185645.dkr.ecr.ap-southeast-2.amazonaws.com/sean-test:latest
